### PR TITLE
Add a graphics tweaks section

### PR DESCRIPTION
**Pull request by FleetAdmiralButter**
Hi there,

I've spent some time (possibly a bit too much) experimenting with the graphics settings in-game running under Crossover to work out what's worth tweaking and what isn't.

For example, options such as LOD and texture filtering really improve how the game looks, while having little impact on FPS. Ditto for Shadow Cascading.

Other options, like Tessellation, don't play nice with Crossover at all and halve FPS is some areas while providing no improvement to graphics.

I've documented my findings here in the README - please let me know if this isn't the right spot.

Cheers.

### CODE REVIEW

**Comment by seathasky** [comment]
As much as I appreciate the effort put in here and can actually see some value, something like this is very much preference of the user. I'm actually in the process of downsizing the page as it already has too much information overload and adding on to it will only get more confusing.

Lets brainstorm here.

What if we made a place for stuff like this but maybe not on the main page. Just like Public testing, it links to a separate page. Maybe setup another PR on a separate page and link to it somewhere on the main page in a tiny section. And we can go from there. 

Maybe include that they are your custom settings/preference as some users prefer different things. I'd include screenshots/videos as well to be more thorough. Not everyone is running the same spec and can get away with a lot better graphics, or vice versa. I don't really think one size fits all really works here when it comes to in game settings. 

The page could possibly be more like a "these are the settings i use" type thing. I still not sure what or how this would work. 

---

A better option and more viable in my opinion **before you start anything** is to create something in the issue tracker similar to how were doing public testing here: https://github.com/seathasky/FF14-MAC_ModSupport/issues/16. I'd probably be more on board with that, as other users can easily submit there results.

What are your thoughts?

**Comment by FleetAdmiralButter** [comment]
Hey @seathasky, thanks for the feedback. Creating a separate "Graphics Settings" folder sounds like a good idea - there could be individual READMEs in there for people with different specs.

Issue tracker would seem like the next best place for this, if the above might possibly result in too many separate README files.

I'm happy to rejig this to go either way.

That being said - I think it might be worth including a short warning in the Troubleshooting section about Tessellation settings. I don't know if the problem is specific to M- chips, but setting that to anything other than "Normal" all but breaks the game by halving FPS in random areas.

**Comment by seathasky** [comment]
Hey, another option would to include it on step 2 but in a drop down section like this? 

ezgif-2-9df112b42b80

Again, im trying to reduce information, so a 2nd page might just be the way to go here. Depends on how its done.

The option of having user feedback sounds more appetizing to me as well. So if we link to an issue tracker, that is fine too. 

To your last request, if you want to include something very tiny in the Troubleshooting section, section it off and make it clean and we'll merge your push. I'm okay with that. Warning though, that section is probably one of the first things I will rework as there a too many images there. If anything, you could add it.. and I might tweak it later when I get to redoing the guide. Your contribution would still though.

**Comment by FleetAdmiralButter** [comment]
+1 on the issue tracker. 

I'll look into moving all this over tomorrow (it is quite late where I am) - I can create the issue as well unless you have a certain format in mind that you'd rather use.

**Comment by seathasky** [comment]
> 
> 
> +1 on the issue tracker.
> 
> I'll look into moving all this over tomorrow (it is quite late where I am) - I can create the issue as well unless you have a certain format in mind that you'd rather use.

That sounds great. Go for it, create it! Just make it look clean. You are welcome to link it from "step 2" in a line or 2. If it looks nice, ill merge it right away.

I believe settings are ever evolving with this project. Especially with DXVK and moltenvk updates were seeing lately. Settings for users may change over time.

**Comment by FleetAdmiralButter** [comment]
Hey @seathasky, as discussed I've moved everything over to issue #25.

**Comment by seathasky** [comment]
Merged and Pinned! Thanks Fleet!

**Pull request merged**
